# The project root directory
Cwd: /home/sjh2019/Documents/Work_Junhao/Anninghe_Array/local_eqs_detection/workflows/LOC-FLOW/eqt-real-hypoinv

# Step1: phase detection based on EQTransformer
Eqt:
  # input data (MSEED) and station list (text format should be given)
  mseed_data_dir: ./Data
  stations_text: ./Locations/staloc/stations.txt
  stations_json: ./Locations/staloc/stations.json
  # where to output results
  pks_result_dir: ./Pick/Eqt/results
  pks_4_REAL_dir: ./Pick/Eqt
  # Eqt detection parameters
  eqt_model: /home/sjh2019/Documents/Packages/EQ_Detection/EQTransformer/ModelsAndSampleData/EqT_model.h5
  eqt_eprob: 0.2
  eqt_pprob: 0.1
  eqt_sprob: 0.1
  overlap: 0.3
  batch_size: 100

REAL:
  run_real_dir: ./REAL
  pks_4_REAL_dir: ./Pick/Eqt/2020????
  stations_text: ./Locations/staloc/stations.txt
  stations_real: ./Locations/staloc/stations.real
  # travel time table
  dist_range_in_deg: 1.4
  depth_in_km: 20
  dist_interval: 0.01
  depth_interval: 1
  r_key: 0.3/20/0.02/1/3
  g_key: 1.4/20/0.01/1
  v_key: 6.0/3.3
  s_key: 2/0/4/1/0.5/0.2/1.5/0.5/1.0

Hypoinv:
  run_hypoinv_dir: ./Hypoinv
  phase_files: ./REAL/*.phase_sel.txt
  input_model: ./REAL/tt_db/mymodel.nd
  input_station: ./Locations/staloc/stations.real
  params_file: ./Hypoinv/hyp.command
  # convert to readable format and screen
  err_hor: 5
  err_dep: 5
  max_gap: 300
  max_rms: 0.5
